### ISSUE TITLE
Implement CI/CD pipeline

### ISSUE THREAD

**Issue by odungern** [GfSE/SpecIF-Viewer#6]
... with automated tests.

**Comment by togiberlin** [comment]
In this commit I added a Travis CI build badge. 
https://github.com/GfSE/SpecIF-Viewer/pull/13/commits/a864edc83d93a8a2f0f5686742d37ad423bbef7a

A build badge will only work, if the GfSE GitHub account is registered/linked to Travis. 
Simply register/login with your GH account and Travis should work.

**Comment by odungern** [comment]
Basic pipeline with ts-compiler is operational; ts-conversion and tests are yet to come.
